#  Its a file in which we count change money.....

x = int(input("Enter total Amount :-     "))

rs1 = 0             # For adding total money.... 

rs2 = 0             # For adding total money.... 

rs5 = 0             # For adding total money.... 

rs10 = 0            # For adding total money.... 
rs20 = 0            # For adding total money.... 

rs50 = 0            # For adding total money.... 

rs100 = 0           # For adding total money.... 

rs200 = 0           # For adding total money.... 

rs500 = 0           # For adding total money.... 

rs2000 = 0          # For adding total money.... 


one = 1                     # element containing money......

two = 2                     # element containing money......

five = 5                    # element containing money......

ten = 10                    # element containing money......

twenty = 20                 # element containing money......

fifty = 50                  # element containing money......

hundred = 100               # element containing money......

t_hun = 200                 # element containing money......

f_hun = 500                 # element containing money......

t_thous = 2000              # element containing money......