#  Its a file in which we count change money.....

x = int(input("Enter total Amount :-     "))

rs1 = 0             # For adding total money.... 

rs2 = 0             # For adding total money.... 

rs5 = 0             # For adding total money.... 

rs10 = 0            # For adding total money.... 
rs20 = 0            # For adding total money.... 

rs50 = 0            # For adding total money.... 

rs100 = 0           # For adding total money.... 

rs200 = 0           # For adding total money.... 

rs500 = 0           # For adding total money.... 

rs2000 = 0          # For adding total money.... 